### ISSUE TITLE
go mod tidy warning

### ISSUE THREAD

**Issue by Oudwins** [axzilla/goilerplate-quickstart#2]
Hey I am just testing this for awesome-templ. When I run go mod tidy I get the following warning. Just thought I would let you know:

```bash
go: finding module for package github.com/axzilla/goilerplate-quickstart/ui/pages
go: github.com/axzilla/goilerplate-quickstart imports
        github.com/axzilla/goilerplate-quickstart/ui/pages: no matching versions for query "latest"
```

edit: to be clear not very important as the site works anyway

**Comment by Oudwins** [comment]
Also goilerplate is awesome. My thoughts on making it a shadcn port or something else are that I think shadcn port has merit in that people will be able to migrate their configs without much trouble. So if it matters at all my vote would go to keeping it as close to shadcn as possible while diverging only if you feel like there is a strong reason to

**Comment by axzilla** [comment]
Hey @Oudwins,

Thanks for testing and for the feedback! The warning you're seeing with `go mod tidy` is actually normal behavior for a template project like this. It occurs because Go tries to find the local packages online, but can't (and shouldn't) find them since they're part of the local project structure.

This warning doesn't affect the functionality and will disappear once you rename the module to your own project name.

Thanks also for the feedback regarding shadcn - really appreciate your thoughts on this!
